### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Wuschli** [Wuschli/TutelMapper#1]
## MVP ToDo
- [x] Add Export Feature
- [x] Add Tile Collection Preview
- [ ] Add Fill Tool
- [ ] Add Options to draw Hex Coordinates
- [ ] Create Custom Tilesets
- [ ] Add Note-Taking / Hex Description Feature
- [x] Create ReadMe
- [ ] Create Logo
- [ ] Publish in Windows Store

## Wishlist (in no particular order)
* Half-Grid Support (https://twitter.com/OskSta/status/1448248658865049605?s=20&t=1rVKDcCVJZIJBIDu0KlP5Q)
* Scriptable Map Generators
* Map Resizing
* Adjustable Background and Grid Rendering
* Rotating and Mirroring Tiles
* Tile Eyedropper
* Fog of War
* Player View (maybe in separate window or as remote cast)
* Adjustable Grid and Background Rendering
* Sub-Grids (https://welshpiper.com/hex-based-campaign-design-part-1/)
